### PR TITLE
Backfilling bootstrap v4.0.0

### PR DESCRIPTION
**Pull request by sesemaya**

### CODE REVIEW

**Comment by djibe** [comment]
Love it !
Thanks

**Comment by djibe** [comment]
Ripple - wave-effect (waves-attach) are not present anymore ?

**Comment by sesemaya** [comment]
Hi @djibe `waves` have been removed from the latest version (by the way, `textarea auto resize` is removed, too). The reason is that these third party plugins can be used without any modifications, unlike `pickadate` as its CSS and JavaScript have to be modified to work with Material. Leaving out these third party plugins can 1) bring down the size of the CSS and JavaScript of this project a bit, 2)  provide some flexibility for developers to use their preferred `waves` plugin. Having said that, the initial idea included a migration doc covering these changes but I was not able to write that up in time of the stable v4 release.

In the meantime, a quick guide here:
- The JavaScript plugin used in alpha and beta to adjust the height of the textarea automatically (i.e. `textarea-autosize`) is: https://github.com/javierjulio/textarea-autosize
- The JavaScript plugin used in alpha and beta to create the ripple effect on click (i.e. `waves`) is : http://fian.my.id/Waves/#start

**Comment by sesemaya** [comment]
Hi @djibe I have created #167 to track migration doc progress

**Pull request merged**
