### PR TITLE
Bowerification. First step JS.

### PR DESCRIPTION
**Pull request by devel-pa**
Hi, as I promised I've added bower. Feel free to comment anything that you're thinking is wrong.

### CODE REVIEW

**Comment by devel-pa** [comment]
I've seen a small issue with `grunt-bowerconcat` (issue is closed but not fixed on their repository) and I will replace it in the next pull request with `grunt-bower` which looks more appropriate for the future refactoring.

**Comment by modius** [comment]
Thanks for the PR!  We're right at the tail end of a big design project -- we'll look at a merge mid next week.

**Comment by sesemaya** [comment]
@devel-pa thanks for the pull request. however things have changed quite a lot, for example, external js libraries (apart from bootstrap and modernizr because they are customised) are all separated from material's base js and loaded via cdn. as a result, there happens to be a lot of conflicts. as i'm not familiar with `grunt-bower` stuff, would you mind work out a new version based on the current master? that will be very much appreciated.

**Comment by devel-pa** [comment]
@sesemaya I will make another try. You have to run before everything `grunt` once to have all the libraries set correctly. 

In fact what is done separates the external libraries from your code and allow others to chose to have them from whichever place they want.

**Pull request closed without merging**
